# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Creamo Studio"
email: 'judi0713@foxmail.com'
description: "Creamo = Create More"
sub_description: "Come from China. Aim to create more interesting software. Making a better world:-D"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://creamo.studio" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 'judi0713'
github_username: 'CM-Studio'
medium_username: ''
section_title: 'Latest Work'
section_subtitle: 'This is our works.'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate
timezone: Asia/Shanghai
future: true

### Phantom settings
paginate: 5
footer_text: '© 2019 Creamo Studio'
admin_name: 'Creamo Studio'
google_analytics: "UA-9999999-99" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  # - { url: '/about', text: 'About' }
